[package]
name = "ataqu-domain-aegis"
version = "0.1.0"
edition = "2024"

[dependencies]
ataqu-kernel = { path = '../ataqu-kernel' }
ataqu-security = { version = "0.1.0", path = "../ataqu-security" }
uuid = { version = '1.24.0', features = ['v7'] }
thiserror = '2.0.18'
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1.91"
base32 = "0.5"
hmac = "0.12"
sha1 = "0.10"
rand = "0.8"
urlencoding = "2.1"
