// Re-export all pivot-related hooks and types from the shared API client
export {
  useListDocuments,
  useCreateDocument,
  useGetDocument,
  useUpdateDocument,
  useDeleteDocument,
  useListDocumentVersions,
  useListDocumentBlocks,
  useCreateBlock,
  useListDatabases,
  useCreateDatabase,
  useGetDatabase,
  useDeleteDatabase,
  useListDatabaseRows,
  useCreateDatabaseRow,
  useUpdateDatabaseRow,
  useDeleteDatabaseRow,
  useSearch,
  useListTemplates,
  useCreateTemplate,
  useApplyTemplate,
  useListDocumentRelations,
  useCreateDocumentRelation,
  useDeleteDocumentRelation,
  // Types
  type Document,
  type Database,
  type DatabaseRow,
  type Block,
  type Template,
  type DocumentVersion,
  type Relation,
  type SearchResult,
  type PaginatedResponse,
} from '@ataqu/api-client';
