[package]
name = "ataqu-infra-repositories"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1.44"
uuid = { version = "1.24.0", features = ["v4", "serde"] }
sqlx = { version = "0.9.0", features = ["postgres"] }
sea-orm = { version = "2.0.0-rc.41", features = ["sqlx-postgres", "runtime-tokio-rustls", "with-uuid", "with-json"] }
serde_json = "1.0.151"
