[package]
name = "ataqu-infra-repositories"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.20.3"
chrono = { version = "0.4.45", features = ["serde"] }
ataqu-security = { path = "../ataqu-security" }
ataqu-domain-aegis = { path = "../ataqu-domain-aegis" }
ataqu-kernel = { path = "../ataqu-kernel" }
tracing = "0.1.44"
uuid = { version = "1.24.0", features = ["v4", "serde"] }
sqlx = { version = "0.9.0", features = ["postgres"] }
sea-orm = { version = "2.0.0-rc.41", features = ["sqlx-postgres", "runtime-tokio-rustls", "with-uuid", "with-chrono"] }
tokio = { version = "1.53.1", features = ["rt", "rt-multi-thread"] }
async-trait = "0.1"
