[package]
name = "ataqu-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
uuid = { version = "1.24.0", features = ["v4", "v5", "v7", "serde"] }
anyhow = "1.0.103"
ataqu-application = { path = "../ataqu-application" }
ataqu-kernel = { path = "../ataqu-kernel" }
