[package]
name = "ataqu-infra-migration"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.52.2", features = ["rt", "macros"] }
async-trait = "0.1.74"
sea-orm = { version = "2.0.0-rc.41", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
sea-orm-migration = "2.0.0-rc.41"