//! DIAL domain commands and events.
//!
//! These types are serialized into the `core.outbox` payload column
//! and consumed by the DIAL message ingester and presence projector.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Command: Create a new DIAL channel.
///
/// `tenant_id` and `created_by` originate from the authenticated session.
/// The channel's `channel_id` and `created_at` are generated by the domain
/// layer via injected `IdGenerator` and `Clock` (ADR-013).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateChannel {
    pub tenant_id: Uuid,
    pub name: String,
    pub created_by: Uuid,
}

/// Command: Send a message to a DIAL channel.
///
/// `message_id` and `sent_at` are generated by the domain layer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SendMessage {
    pub tenant_id: Uuid,
    pub channel_id: Uuid,
    pub sender_id: Uuid,
    pub content: String,
}

/// Event: A message was sent to a DIAL channel.
///
/// Emitted by the domain layer and persisted to `core.outbox`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageSent {
    pub tenant_id: Uuid,
    pub message_id: Uuid,
    pub channel_id: Uuid,
    pub sender_id: Uuid,
    pub content: String,
    pub sent_at: DateTime<Utc>,
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Build a deterministic UUID from a single repeated byte.
    fn uuid_from_byte(b: u8) -> Uuid {
        Uuid::from_bytes([b; 16])
    }

    #[test]
    fn create_channel_round_trips() {
        let cmd = CreateChannel {
            tenant_id: uuid_from_byte(1),
            name: "general".to_string(),
            created_by: uuid_from_byte(2),
        };
        let json = serde_json::to_string(&cmd).expect("serialize");
        let back: CreateChannel = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(cmd.tenant_id, back.tenant_id);
        assert_eq!(cmd.name, back.name);
        assert_eq!(cmd.created_by, back.created_by);
    }

    #[test]
    fn send_message_round_trips() {
        let cmd = SendMessage {
            tenant_id: uuid_from_byte(1),
            channel_id: uuid_from_byte(2),
            sender_id: uuid_from_byte(3),
            content: "Hello, world!".to_string(),
        };
        let json = serde_json::to_string(&cmd).expect("serialize");
        let back: SendMessage = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(cmd.tenant_id, back.tenant_id);
        assert_eq!(cmd.channel_id, back.channel_id);
        assert_eq!(cmd.sender_id, back.sender_id);
        assert_eq!(cmd.content, back.content);
    }

    #[test]
    fn message_sent_round_trips() {
        let evt = MessageSent {
            tenant_id: uuid_from_byte(1),
            message_id: uuid_from_byte(4),
            channel_id: uuid_from_byte(2),
            sender_id: uuid_from_byte(3),
            content: "Hello, world!".to_string(),
            sent_at: DateTime::parse_from_rfc3339("2026-08-01T12:00:00Z")
                .unwrap()
                .with_timezone(&Utc),
        };
        let json = serde_json::to_string(&evt).expect("serialize");
        let back: MessageSent = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(evt.message_id, back.message_id);
        assert_eq!(evt.sent_at, back.sent_at);
    }

    #[test]
    fn message_sent_timestamp_serializes_as_iso8601() {
        let evt = MessageSent {
            tenant_id: uuid_from_byte(1),
            message_id: uuid_from_byte(2),
            channel_id: uuid_from_byte(3),
            sender_id: uuid_from_byte(4),
            content: "hi".to_string(),
            sent_at: DateTime::parse_from_rfc3339("2026-08-01T12:00:00Z")
                .unwrap()
                .with_timezone(&Utc),
        };
        let json = serde_json::to_string(&evt).expect("serialize");
        assert!(
            json.contains("\"2026-08-01T12:00:00Z\""),
            "expected ISO 8601 timestamp in JSON, got: {json}"
        );
    }

    #[test]
    fn send_message_allows_empty_content() {
        // The contract layer does not validate content — that is the domain's
        // responsibility. We only verify that empty strings survive round-trip.
        let cmd = SendMessage {
            tenant_id: uuid_from_byte(1),
            channel_id: uuid_from_byte(2),
            sender_id: uuid_from_byte(3),
            content: String::new(),
        };
        let json = serde_json::to_string(&cmd).expect("serialize");
        let back: SendMessage = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back.content, "");
    }
}
