//! VAULT domain commands and events.
//!
//! These types are serialized into the `core.outbox` payload column
//! and consumed by the VAULT inventory projector.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Command: Create a new VAULT product.
///
/// `product_id` and `created_at` are generated by the domain layer.
/// `initial_stock` represents the starting quantity (must be >= 0,
/// enforced by domain validation and ADR-023 DB constraint).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateProduct {
    pub tenant_id: Uuid,
    pub name: String,
    pub sku: String,
    pub initial_stock: i64,
}

/// Command: Adjust stock for a VAULT product.
///
/// `delta` may be negative (e.g., returns, damage). The domain layer
/// computes `new_quantity` and validates the overflow protection
/// constraint (ADR-023: `stock_quantity >= 0`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateStock {
    pub tenant_id: Uuid,
    pub product_id: Uuid,
    pub delta: i64,
    pub reason: String,
}

/// Event: Stock was adjusted for a VAULT product.
///
/// Emitted by the domain layer and persisted to `core.outbox`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StockAdjusted {
    pub tenant_id: Uuid,
    pub product_id: Uuid,
    pub delta: i64,
    pub new_quantity: i64,
    pub reason: String,
    pub adjusted_at: DateTime<Utc>,
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Build a deterministic UUID from a single repeated byte.
    fn uuid_from_byte(b: u8) -> Uuid {
        Uuid::from_bytes([b; 16])
    }

    #[test]
    fn create_product_round_trips() {
        let cmd = CreateProduct {
            tenant_id: uuid_from_byte(1),
            name: "Widget".to_string(),
            sku: "WID-001".to_string(),
            initial_stock: 100,
        };
        let json = serde_json::to_string(&cmd).expect("serialize");
        let back: CreateProduct = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(cmd.tenant_id, back.tenant_id);
        assert_eq!(cmd.name, back.name);
        assert_eq!(cmd.sku, back.sku);
        assert_eq!(cmd.initial_stock, back.initial_stock);
    }

    #[test]
    fn update_stock_round_trips() {
        let cmd = UpdateStock {
            tenant_id: uuid_from_byte(1),
            product_id: uuid_from_byte(2),
            delta: -5,
            reason: "damaged".to_string(),
        };
        let json = serde_json::to_string(&cmd).expect("serialize");
        let back: UpdateStock = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(cmd.product_id, back.product_id);
        assert_eq!(cmd.delta, back.delta);
        assert_eq!(cmd.reason, back.reason);
    }

    #[test]
    fn stock_adjusted_round_trips() {
        let evt = StockAdjusted {
            tenant_id: uuid_from_byte(1),
            product_id: uuid_from_byte(2),
            delta: -5,
            new_quantity: 95,
            reason: "damaged".to_string(),
            adjusted_at: DateTime::parse_from_rfc3339("2026-08-01T12:00:00Z")
                .unwrap()
                .with_timezone(&Utc),
        };
        let json = serde_json::to_string(&evt).expect("serialize");
        let back: StockAdjusted = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(evt.product_id, back.product_id);
        assert_eq!(evt.delta, back.delta);
        assert_eq!(evt.new_quantity, back.new_quantity);
        assert_eq!(evt.reason, back.reason);
        assert_eq!(evt.adjusted_at, back.adjusted_at);
    }

    #[test]
    fn update_stock_supports_negative_delta() {
        let cmd = UpdateStock {
            tenant_id: uuid_from_byte(1),
            product_id: uuid_from_byte(2),
            delta: -10,
            reason: "return".to_string(),
        };
        let json = serde_json::to_string(&cmd).expect("serialize");
        assert!(
            json.contains("-10"),
            "expected negative delta in JSON, got: {json}"
        );
    }

    #[test]
    fn create_product_supports_zero_initial_stock() {
        let cmd = CreateProduct {
            tenant_id: uuid_from_byte(1),
            name: "Backorder Item".to_string(),
            sku: "BO-001".to_string(),
            initial_stock: 0,
        };
        let json = serde_json::to_string(&cmd).expect("serialize");
        let back: CreateProduct = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back.initial_stock, 0);
    }
}
